# Python Dictionary to map variables to their respective clusters

cluster_names = {
        'alter_W': 'Age',
        'BORG_W': 'Dyspnea',
        'BPDIA_W': 'Blood Pressure',
        'BPSYS_W': 'Blood Pressure',
        'BREATH_W': 'Respiratory Rate',
        'COPDDIA_W': 'COPD and Symptoms Duration',
        'COPDSYM_W': 'COPD and Symptoms Duration',
        'DIST_W': 'Exercise Capacity',
        'DLCOMP_W': 'Diffusion Capacity',
        'DLCOPP_W': 'Diffusion Capacity',
        'DLCOVAMP_W': 'Diffusion Capacity',
        'DLCOVAPP_W': 'Diffusion Capacity',
        'ERVL_W': 'Expiratory Reserve',
        'ERVLP_W': 'Expiratory Reserve',
        'ERVP_W': 'Expiratory Reserve',
        'ERVPP_W': 'Expiratory Reserve',
        'FENO': 'Inflammatory Markers',
        'FEVL_W': 'Diffusion Capacity',
        'FEVLP_W': 'Diffusion Capacity',
        'FEVP_W': 'Diffusion Capacity',
        'FEVPP_W': 'Diffusion Capacity',
        'FEVVCP_W': 'Diffusion Capacity',
        'FEVVCPP_W': 'Diffusion Capacity',
        'FVCL_W': 'Lung Volume Parameters',
        'FVCLP_W': 'Lung Volume Parameters',
        'FVCP_W': 'Lung Capacity Percentage',
        'FVCPP_W': 'Lung Capacity Percentage',
        'HEIGHT_W': 'Height',
        'HHR_W': 'Exercise Heart Rate',
        'HR_W': 'Exercise Heart Rate',
        'HRREST_W': 'Exercise Heart Rate',
        'ITGVL_W': 'Lung Intrathoracic Gas',
        'ITGVLP_W': 'Lung Intrathoracic Gas',
        'ITGVP_W': 'Lung Intrathoracic Gas',
        'ITGVPP_W': 'Lung Intrathoracic Gas',
        'LOXAT_W': 'Exercise Oxygen Desaturation',
        'MEDDIS_W': 'Medication Count',
        'MEF25P_W': 'Lung Flow Measurements',
        'MEF25PP_W': 'Lung Flow Measurements',
        'MEF50LS_W': 'Diffusion Capacity',
        'MEF50LSP_W': 'Diffusion Capacity',
        'MEF50P_W': 'Diffusion Capacity',
        'MEF50PP_W': 'Diffusion Capacity',
        'MEF75LS_W': 'Diffusion Capacity',
        'MEF75LSP_W': 'Diffusion Capacity',
        'MEF75P_W': 'Diffusion Capacity',
        'MEF75PP_W': 'Diffusion Capacity',
        'NO1_W': 'Inflammatory Markers',
        'PEFLS_W': 'Diffusion Capacity',
        'PEFLSP_W': 'Diffusion Capacity',
        'PEFP_W': 'Diffusion Capacity',
        'PEFPP_W': 'Diffusion Capacity',
        'POXSAT_W': 'Baseline Oxygen Levels',
        'POXSAT_WDT6_W': 'Baseline Oxygen Levels',
        'PY_W': 'Smoking History',
        'RVL_W': 'Lung Intrathoracic Gas',
        'RVLP_W': 'Lung Intrathoracic Gas',
        'RVP_W': 'Lung Intrathoracic Gas',
        'RVPP_W': 'Lung Intrathoracic Gas',
        'RVTLCP_W': 'Lung Intrathoracic Gas',
        'RVTLCPP_W': 'Lung Intrathoracic Gas',
        'TLCL_W': 'Lung Intrathoracic Gas',
        'TLCLP_W': 'Lung Intrathoracic Gas',
        'TLCP_W': 'Lung Intrathoracic Gas',
        'TLCPP_W': 'Lung Intrathoracic Gas',
        'VALP_W': 'Ventilation Efficiency',
        'VAPP_W': 'Ventilation Efficiency',
        'VCL_W': 'Lung Volume Parameters',
        'VCLP_W': 'Lung Volume Parameters',
        'VCMAXL_W': 'Lung Volume Parameters',
        'VCMAXLP_W': 'Lung Volume Parameters',
        'VCMAXP_W': 'Lung Capacity Percentage',
        'VCMAXPP_W': 'Lung Capacity Percentage',
        'VCP_W': 'Lung Capacity Percentage',
        'VCPP_W': 'Lung Capacity Percentage',
        'WEIGHT_W': 'Body Weight'
        }
